version: "3.5"
services:
  bambulab-exporter:
    image: ghcr.io/scrin/bambulab-exporter
    container_name: bambulab-exporter
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      BAMBULAB_EXPORTER_PRINTER_HOST: "192.168.1.100" # your printer's IP address
      BAMBULAB_EXPORTER_PRINTER_SERIAL: "1234567890" # your printer's serial number
      BAMBULAB_EXPORTER_PRINTER_ACCESS_CODE: "1234567890" # your printer's access code
      BAMBULAB_EXPORTER_PRINTER_NAME: "" # optional, a name for the printer to differentiate between multiple printers
      BAMBULAB_EXPORTER_LOG_LEVEL: "info" # optional, log level: trace, debug, info, warn, error, fatal, panic
